### PR TITLE
Changed Databrocker OnClick

### PR DESCRIPTION
**Pull request by fubaWoW**
#### Click on Databroker now do the following
 - **Left Click**
 Toggle the History Window  

 - **Right Click**
 Toggle the Option Menu  

 - **Shift + Left Click**
 Toggle the AddOn

also added ElvUI Skin for the History Window if ElvUI is installed, here a preview:
image

maybe you can add this to your addon?
many thanks ;)

### CODE REVIEW

**Comment by Ketho** [comment]
Thanks looks good to me, and I somehow missed the initial PR. I won't be able to release a version until next week since I'm busy sorry :(

**Comment by fubaWoW** [comment]
all fine!
just like your addon and wanted to add something :P
thanks for the update!

**Comment by fubaWoW** [comment]
oh damn...
i see i did not exclude the ``.vscode`` folder from the project...
maybe you can remove it?
sorry for that!

**Comment by Ketho** [comment]
Oh, the `.vscode` folder already was in there from me 😅

don't worry, it won't show up in the addon zip

**Pull request merged**
